### ISSUE TITLE
Use std::uninitialized_fill ?

### ISSUE THREAD

**Issue by guptadivyansh** [orlp/devector#1]
Hi, I was curious as to why you haven't used std::uninitialized_fill and std::uninitialized_copy?
Was there any specific reason for writing your own functions?

https://github.com/orlp/devector/blob/master/devector.h#L586

**Comment by orlp** [comment]
`std::unitialized_fill` and `std::unitialized_copy` are not allocator-aware.

Note that if you're studying the code this container is still WIP, and some things below [this line](https://github.com/orlp/devector/blob/master/devector.h#L348) are bugged or not done yet.

**Comment by guptadivyansh** [comment]
Oh, I see.

Thanks!
